[build]
buildCommand = "sh build.sh"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"
releaseCommand = "cd backend && /app/venv/bin/python3 init_db.py"
